lock_submit:
  field: lock
  value: submit
  regex: False
  dependencies:
    mariadb:
      query: SELECT ts FROM {table} WHERE account=\'{address}\'
  exclude:
    type: alias
wrong_comma:
  field: All
  value: '[0-9,a-z,A-Z,.,@]+\,.*$'
  regex: True
  exclude:
    field: dn