lock_submit:
  type: lock_submit
  field: lock
  value: submit
  regex: False
  mariadb_query: SELECT ts FROM {table} WHERE account=\'{address}\'
wrong_comma:
  type: general
  field: All
  value: '[0-9,a-z,A-Z,.,@]+\,.*$'
  regex: True
  exclude:
    field: dn